name: Create Issues
on:
  issue_comment:
    type: [created]

jobs:
  create_issues:

    runs-on: ubuntu-latest

    steps:
    - uses: paulovitin/create-issues@0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
